# Generated by Django 4.2.3 on 2023-07-09 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Maker",
            new_name="Makers",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
    ]
